now choosing an initial zoom value which fits the entire graph in the canvas
nickBes/csv_to_graph pull request #23
Opened 2022-03-25 22:28 UTC by MaderNoob

2022-03-26 14:21 UTC, nickBes requested changes
Zooming isn't enough because it only assures that the graph would fit the canvas if it'd be in the center of the screen, but it isn't. So we also need to move the graph to the center

2022-03-26 14:21 UTC, nickBes commented on index.js
> +        // to zoom the y coordinates we want to multiply the height of each point.
why do we need to multiply the height if we don't do that in our zooming functionality. what difference does it make?

2022-03-26 17:14 UTC, MaderNoob commented on index.js
> +        // to zoom the y coordinates we want to multiply the height of each point.
Multiplying the height is like zooming out from the bottom left point. If i were to zoom out from the top-left, i would just multiply the y value, but i want to zoom out from the origin, which is bottom left, so i must mutliply the height instead.

2022-03-28 12:38 UTC, nickBes commented on index.js
> +    const height = Math.abs(boundaries.bottom - boundaries.top);
same here but switch the order to make it `top - bottom`

2022-03-28 12:43 UTC, nickBes commented on index.js
> +    points = points.map((point) => zoomPoint(point, zoomFactor, origin))
why are you mapping the points twice? just don't pass the points array in the method.

2022-03-28 12:48 UTC, nickBes commented on index.js
> +    const movement = [-boundariesAfterZoom.left, -(boundariesAfterZoom.bottom - canvas.height)]
maybe i'd explain why you make these calculations

2022-03-28 12:59 UTC, MaderNoob commented on index.js
> +    const height = Math.abs(boundaries.bottom - boundaries.top);
no, bottom > top

2022-03-28 13:10 UTC, merged