the graph is now full screen with a side menu
nickBes/csv_to_graph pull request #43
Opened 2022-03-31 21:55 UTC by MaderNoob

2022-03-31 22:25 UTC, nickBes requested changes
cute

2022-03-31 22:25 UTC, nickBes commented on scripts/graph.js
> +document.onmousemove = event => {
I'd change it into `document.body` as it's continues on dragging when I'm on an other window

2022-04-01 18:35 UTC, MaderNoob commented on scripts/graph.js
> +document.onmousemove = event => {
Why isn't it desired behaviour?

2022-04-01 18:47 UTC, nickBes approved these changes

2022-04-01 18:48 UTC, merged